#!/bin/bash -
#===============================================================================
#
FILE=minfocreate
VER=0.5a
#
#         USAGE: ./minfocreate
#
#   DESCRIPTION: Simple NFO file creator that uses Mediainfo and imdbdump.
#
#       OPTIONS:
#  REQUIREMENTS: awk, cat, curl, cut, egrep, elinks, grep, head, sed, tr, uniq wc and wget.
#          BUGS: ---
#         NOTES:
#        AUTHOR: Mike Redd (MikereDD), mikeredd@mobileinfern.us
#  ORGANIZATION: Dumb Terminal Team
#       CREATED: 03/27/2011 02:35:12 PDT
#      REVISION: 06/27/2014 18:48:05 PDT
#===============================================================================

###########################
# http://dt.tehspork.com
# Dumb Terminal
# Smaller than Life Projects
# Main Page: http://dt.tehspork.com
# Git Repo: https://github.com/dumbterminal/
# By: MikereDD & veekahn
# email: dumbterminal -at- tehspork.com
#
# projects - at - Git Hub for use with
# miNfo - Mediainfo .nfo Creator
# DT-miNfo        -  https://github.com/dumbterminal/DT-miNfo
# MI nfoCreate    -  https://github.com/dumbterminal/DT-miNfo/blob/master/minfocreate
# iMDB-Dump       -  https://github.com/dumbterminal/DT-miNfo/blob/master/imdbdump
# iMDB-ThumbGrab  -  https://github.com/dumbterminal/DT-miNfo/blob/master/imdbthumbgrab
###########################
# Example of finished nfo|htm files here
#
# <a href="https://github.com/dumbterminal/DT-miNfo/blob/master/example-created.nfo">Click for Example NFO File</a>
#
# <a href="https://github.com/dumbterminal/DT-miNfo/blob/master/example-created.htm">Click for Example HTM(L) File</a>
#
###########################
#
# MI NFOcreate Depends on
# iMDB-Dump  -  https://github.com/dumbterminal/DT-miNfo/blob/master/imdbdump
# iMDB-ThumbGrab  -  https://github.com/dumbterminal/DT-miNfo/blob/master/imdbthumbgrab
# Mediainfo  -  http://mediainfo.sourceforge.net/en
# ELinks  -  http://elinks.or.cz
# Curl  -  http://curl.haxx.se
#
############################

#
############################
############################
#####    DIR   PATH    #####
############################
############################
#
# Path to Working Directory
VIDEODIR="$HOME/Rip/done"
# Path to miNfo Directory
miNfo="$HOME/tmp/miNfo"
# Path to SAVE nfo folder
SAVE="$miNfo/nfo"
# Path inside Temp Directory Script works in
TMPWRK="$miNfo/wrk"
# Cleanup first
if [ -e $TMPWRK ]; then
  rm $TMPWRK/*
fi
#
############################
############################
#####  END DIR   PATH  #####
############################
############################

############################
############################
#####  SCRIPTS  PATH   #####
############################
############################
#
# Path to imdbdump-nc
IMDUMP="$HOME/bin/imdbdump-nc"
POSTER="$HOME/tmp/imdbdump/posters"
# Path to minfohelp directory containing tag.txt, pre1.txt and pre2.txt Files - files w/get packed w/finished script.
MINFOHELP="$miNfo/minfohelp"
# Path to imdb-thumbgrab.sh
IMDTHUM="$miNfo/imdbthumbgrab"
THUMBNAIL="$TTITLE.jpg"
#
############################
############################
####  END SCRIPTS PATH  ####
############################
############################

############################
############################
#####   APPS  PATH     #####
############################
############################
#
# Path to Mediainfo
MINFO=`which mediainfo`
AWK=`which awk`
CAT=`which cat`
GREP=`which grep`
TAIL=`which tail`
WC=`which wc`
#
############################
############################
#####  END APPS PATH   #####
############################
############################

############################
############################
#### START   QUESTIONS  ####
############################
############################
#
# Title
cd $VIDEODIR
TITLE=$(ls | sed '$s/....$//')
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%% Name your .nfo and .htm files here"
echo "%%  Default Title: $TITLE"
echo "%% Would you like to Name the Title?"
echo "%% Press: (y|n) "
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
read TITLE
case $TITLE in
	y|yes)
	  echo "Enter Title Name: "
          echo "------------------"
	   	read TITLE ;;
	n|no)
		TITLE=$(ls | sed '$s/....$//') ;;
	*)
	echo "Error Valid Choices are y|n"
	exit 1 ;;
    esac
echo ""
echo ""
# ttcode
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo "%% iMBD Dump needs the title "
echo "%%   from http://imdb.com"
#echo "%% Example:  http://www.imdb.com/title/tt0083907"
echo "%% title would be Evil Dead"
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo ""
echo " Type in the imdb movie title then press Enter"
read TTITLE
echo ""
echo "Your title: $TTITLE"
echo ""
#
############################
############################
###  END START QUESTIONS ###
############################
############################

############################
############################
#####      START       #####
############################
############################
#

echo " $FILE V. $VER"
sleep 3
# start
cd $VIDEODIR
echo " -- MI - NFOcreate -- "
echo " "
sleep 2
mkdir -p $SAVE/$TITLE
sleep 2
# Create the NFO TEXT File
echo " -- Creating $TITLE.nfo -- "
echo " "
sleep 2
$MINFO * >> $TMPWRK/$TITLE.nfo
$IMDUMP -t "$TTITLE" > $TMPWRK/$TTITLE.temp
$CAT $MINFOHELP/tag.txt $TMPWRK/$TTITLE.temp $TMPWRK/$TITLE.nfo >> $SAVE/$TITLE/$TITLE.nfo
echo " -- Done Creating $TITLE.nfo File -- "
echo " "
sleep 1
echo " -- Creating $TITLE.htm File -- "
sleep 2
# Create the NFO in HTML File
$MINFO --Output=HTML * >> $TMPWRK/$TITLE.htm
lines=$($WC -l $TMPWRK/$TITLE.htm | $AWK '{print $1}')
x="$lines"
y="8"
sub=$(($x - $y))
$TAIL -$sub $TMPWRK/$TITLE.htm | $AWK -F\| '{print $1}' >> $TMPWRK/prt2.htm
$CAT $TMPWRK/$TITLE.htm | $GREP "General" -B5 -A0 | $AWK -F\| '{print $1}' >> $TMPWRK/prt1.htm
$CAT $TMPWRK/prt1.htm $MINFOHELP/pre1.txt >>  $TMPWRK/prt3.htm
$CAT $MINFOHELP/pre2.txt $TMPWRK/prt2.htm >> $TMPWRK/prt4.htm
echo ""
$CAT $TMPWRK/prt3.htm $MINFOHELP/tag.txt $TMPWRK/$TTITLE.temp $TMPWRK/prt4.htm >> $SAVE/$TITLE/$TITLE.htm
echo " "
sleep 1
echo " -- Done Creating $TITLE.htm File -- "
echo " "
sleep 1
#echo " -- Starting iMDB ThumbGrab -- "
echo " Moving Poster "
sleep 1
#$IMDTHUM $TTCODE
sleep 1
#echo " -- Done with iMDB ThumbGrab -- "
echo " -- Renaming and Moving Thumbnail -- "
mv $POSTER/$TTITLE.jpg $SAVE/$TITLE/$TITLE.jpg
echo " -- Done Renaming and Moving Thumbnail --"
echo " "
sleep 1
echo " -- Thank You for Using MI-nfoCreate -- "
echo " -- a script by: MreDD -- "
sleep 1
echo " fin "

#
############################
############################
#####        END       #####
############################
############################

exit 0
